
# Generic things to save for the run
Project_Utility:
  name: test # Project title
  parent_dir: "."
  save: True # Set to False if testing

  extra_dirs:
    results_dir: "results" # Directory to save results
    model_dir: "models" # Directory to save models
    plot_dir: "plots" # Directory to save plots
    log_dir: "logs" # Directory to save logs
    input_dir: "input_files"

  output:
    print: 1.0e+1 # When to print the loss and other information
    saveat: 1.0e+3 # When to save the parameters and update plots

# FE Problem to solve defined in a separate yaml file
fe_input_file: "inputs/fe_input_file.yaml"

# ML parameters
ml_input_file: "inputs/ml_input_file.yaml"

Sampler:
  training:
    name: "uniform"
    kwargs:
      mins: [0.] # List of min values
      maxes: [2.] # List of max values
      samples: [10] # List of number of samples
  
  testing:
    name: "uniform"
    kwargs:
      between_training: True
      mins: [0.] # List of min values
      maxes: [2.] # List of max values
      samples: [10] # List of number of samples

# Controls what should be plotted through the run
# could add custom plots here to be triggered
Plotting:
  loss: True
  learning_rate: True