site_name: My Docs

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search:
        # See https://github.com/squidfunk/mkdocs-material/discussions/8116#discussioncomment-12632752
        # and https://github.com/patrick-kidger/equinox/issues/984
        # In particular this allows for searching e.g. 'filter_grad' and to match 'equinox.filter_grad'.
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    # - include_exclude_files:
    #     include:
    #         - ".htaccess"
    #     exclude:
    #         - "_overrides"
    #         - "examples/.ipynb_checkpoints/"
    #         - "examples/MNIST"
    #         - "examples/bert_checkpoint.eqx"
    # - ipynb
    # - hippogriffe:
    #     extra_public_objects:
    #         - equinox.if_array
    #         - jax.ShapeDtypeStruct
    #         - jax.extend.core.ClosedJaxpr
    #         - jax.Device
    #         - jax.sharding.Sharding
    - mkdocstrings:
        handlers:
            python:
                options:
                    force_inspection: true
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    show_bases: false
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: false
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true

nav:
  - Home: index.md

  - API: test.md