site_name: CARDIAX-NNFE Documentation

theme:
    name: material  # Recommended for use with pymdownx extensions
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
    - Home: index.md
    - API: 
        - Main Functionality: api/main_functionality.md
        - Networks: api/networks.md

    - Tutorials:
        - Overview: tutorials/overview.md
        - Configurations: tutorials/configurations.md
        - Prolate Spheroid: tutorials/prolate_spheroid.md

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"
        toc_depth: 4

# This section tells the browser to load MathJax and your custom config
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                paths: ["src"]
                options:
                    force_inspection: true
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    show_bases: false
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: false
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true
