
# Generic things to save for the run
project:
  name: Results # Project title
  parent_dir: "."
  save: True # Set to False if testing
  print_progress: 1.0e+1 # When to print the loss and other information
  save_progress: 1.0e+4 # When to save the parameters and update plots

  extra_dirs:
    results_dir: "results" # Directory to save results
    model_dir: "models" # Directory to save models
    plot_dir: "plots" # Directory to save plots
    log_dir: "logs" # Directory to save logs
    config_dir: "config_files" # Directory to save input files

# FE Problem to solve defined in a separate yaml file
FE: "fe_input_file.yaml"

# All parameters associated with the machine learning part of NNFE
# Split into Network and Optimizer
ML: "ml_input_file.yaml"

# Controls the overall control need for NNFE
NNFE:
  # Number of variables to train
  natural:
    internal:
      u: ["TCa"]

    surface:
      u:
        bc2: ["p"]

  essential:
    u:

  natural_order: ["p", "TCa"]
  essential_order: []

sampler:
  training_sampler: "uniform"
  training_kwargs:
    mins: [0., 0.] # List of min values
    maxes: [120., 60.] # List of max values
    samples: [6, 5] # List of number of samples
  
  testing_sampler: "uniform"
  testing_kwargs:
    between_training: True
    mins: [0., 0.] # List of min values
    maxes: [120., 60.] # List of max values
    samples: [6, 5] # List of number of samples

# Controls what should be plotted through the run
# could add custom plots here to be triggered
plotter:
  plot_loss: True
  plot_lr: True
  plot_sample: True