
# All parameters associated with the machine learning part of NNFE
# Split into Network and Optimizer
Networks:
  key: "random"

  Network1:
    # Which model to use, based on "networks.py"
    name: "ResNet"
    kwargs:
      in_size: 1
      out_size: "dofs" # Can be specified or "dofs" if NNFE
      width_size: 128
      depth: 6
      activation: "elu"
      use_bias: True
      use_final_bias: True

    load_model:
    static: False

  # Network2:
  #   # Which model to use, based on "networks.py"
  #   name: "ResNet"
  #   kwargs:
  #     in_size: 1
  #     out_size: "dofs" # Can be specified or "dofs" if NNFE
  #     width_size: 128
  #     depth: 6
  #     activation: "elu"
  #     use_bias: True
  #     use_final_bias: True

  #   load_model:
  #   static: False

Optimizer:
  name: "adam"
  learning_rate: 1.0e-3
  epochs: 1.e+4
  batch_size: 1.

  scheduler:
    toggle: True
    boundaries: []
    schedules:
      s1:
        name: "exponential_decay"
        kwargs:
          init_value: 1.0e-3
          decay_rate: 1.0e-1
          transition_steps: 1.0e+4

  kwargs:
    learning_rate: