name: Check unittests
run-name: ${{ github.actor }} is testing their code 🚀
on:
  pull_request:
    branches:
    - main
    - 'unittests'
    - 'refactor'
    - 'CI'
  push:
    branches:
    - 'CI'
jobs:
  Run-Unittests:
    runs-on: ubuntu-latest
    container:
      image: kenmeyer17/cardiax_env
    steps:
      #- uses: Jimver/cuda-toolkit@v0.2.15
      #  id: cuda-toolkit
      #  with: 
      #    cuda: '11.8.0'
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - run: echo "Running the following unittests:"
      - run: echo "nodal_stress, linear_elasticity_cube"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check working directory and content
        run: pwd && ls
      - name: Run CARDIAX unittests
        run: python -m unittest
      
      # this is an alias that should be defined by each user
      #- name: Activate virtual environment
      #  run: activate_cardiax_venv
      #- name: Run nodal_stress test
      #  run: python tests/benchmarks/nodal_stress/test_nodal_stress.py
      #- name: Run linear_elasticity_cube test
      #  run: python tests/benchmarks/nodal_stress/test_linear_elasticity_cube.py
        
