
Key: 3 # Either number or "random" for random key
Network:
  # Which model to use, based on "networks.py"
  name: "ResNet"
  kwargs:
    in_size: 1
    out_size: "dofs" # Can be specified or "dofs" if NNFE
    width_size: 128
    depth: 6
    activation: "elu"
    use_bias: True
    use_final_bias: True

  load_model:

Optimizer:
  name: "adam"
  learning_rate: 1.0e-3
  epochs: 1.e+4
  batch_size: 1.

  scheduler:
    toggle: True
    boundaries: []
    list:
      s1:
        name: "exponential_decay"
        kwargs:
          init_value: 1.0e-3
          decay_rate: 1.0e-1
          transition_steps: 1.0e+4

  options:
    learning_rate: